### ISSUE TITLE
Split the init patch into multiple patches

### ISSUE THREAD

**Issue by huster-hh** [acsl-technion/TPT#1]
Hey, I was wondering if it would be possible to split the init patch into multiple patches? It would make it easier to learn and study your system if there were separate patches for changes of host kernel/qemu/guest kernel. What do you think? The init patch is too large and locating your modifications poses a challenge.

**Comment by shaiberg1** [comment]
Hi!

Yes I agree, thanks for the feedback. I'll try and get this done relatively soon. Meanwhile you can clone the base git repo of the sources, then apply TPT's sources directly on it and commit, it will show only the changes I think.

Thanks!

**Comment by huster-hh** [comment]
Hi！

I have several additional questions, and I would be very grateful if you could take the time to answer:

1. In the absence of memory tagging to validate the HPAs assigned to the VM, what would be the implications? Is it solely a security concern? (Given that not all x86 architectures support memory tagging, such as Intel CPU, are there any alternative approaches?)
2. How challenging would it be to integrate TPT with SPT? Have you conducted any testing on its compatibility with SPT? Similar to how Xen's direct paging addresses the inefficient cross-domain page table synchronization between the guest page table and the shadow page table, TPT appears to effectively resolve SPT's synchronization overhead while keeping efficient memory access.
3. Would you be able to provide the Git link for the version of QEMU used? I am still not able to locate a version that aligns with your modifications.

Thanks!

**Comment by shaiberg1** [comment]
Hello!

Happy to help :)

1. It is solely a security concern.
2. I don't think it will be too hard, but it would require extensive changes in KVM. Yap, that is one of the benefits we thought of when designing TPT, to overcome performance limitations by using new hardware technologies.
3. I'm sorry for the delay, I'm a bit swamped, but I'll do my best to split this into patches / find the git commit I've used as a base for the implementation. I will keep you updated


Hope I helped!

**Comment by huster-hh** [comment]
Thank you for taking the time to respond. I appreciate your work in the field of TPT, as it is both captivating and impactful. At present, I am endeavoring to implement TPT on SPT and I have found your insights to be particularly helpful. Thank you for your valuable time and expertise.

**Comment by huster-hh** [comment]
I apologize if I have caused any inconvenience, but I am still struggling to find out about your changes to QEMU. Would it be possible for you to send me the patch for QEMU to my Gmail (hanghhust@gmail.com)? If so, I would be deeply grateful. I have already been able to get your modifications to the host/guest kernel.

**Comment by shaiberg1** [comment]
No worries. I'll make some time tomorrow to find it

**Comment by shaiberg1** [comment]
Hi there!

The commit QEMU is based on is this one:
https://github.com/qemu/qemu/commit/44efeb90b2d06635fd4052fa080b2a2ea480501f

Hope this helps!

I'm closing this issue, but please feel free to send me an email regarding this or any other question.

Thanks,
Shai

**Comment by luzhixing12345** [comment]
The same question. Your paper and project look pretty cool, and I'm also trying to learn how to modify kernel and qemu. It's hard for me to locate your modification, could you please split the init commit? Thanks a lot!
