### ISSUE TITLE
guest kernel panic

### ISSUE THREAD

**Issue by huster-hh** [acsl-technion/TPT#2]
I can find "/proc/kvm-xx" and the gfn_to_hfn in the host, which means the host KVM works well. However, the guest kernel failed to startup because of “Unable to mount root fs on unknown-block”.
<img width="834" alt="image" src="https://github.com/acsl-technion/TPT/assets/6761492/0165337d-9121-4e20-ba74-37940a12d7c3">

I tried to run VM with TPT enabled in 4 steps on the intel platform:
1. make install the host kernel with the default config and install the kvm.ko&kvm-intel.ko
2. make the guest kernel with tpt config and obtain the bzImage
3. make & install qemu
4. run run_virt_general.sh with USER=root & GUEST_DIR & SOURCE_DIR of ubuntu.img generated by "qemu-img create -f qcow2 ubuntu.img 250G" 

Can you help me find out what's wrong? Thanks！

**Comment by shaiberg1** [comment]
Hi @huster-hh !

So I guess this is an issue with the drivers on the host itself. Maybe the default config is somehow missing:
CONFIG_VIRTIO_BLK=y
CONFIG_VIRTIO_PCI=y
or the guest kernel is missing those as well?

Please try and recompile both and let me know if that solved the issue :)

**Comment by huster-hh** [comment]
Hi @shaiberg1 

Thanks for your time.

It still does not work for me. I tried two ways to work around this problem, 1) recompile the host kernel  with CONFIG_VIRTIO_xx=Y and 2) change the "if=virtio" to "if=none", but both failed. Can your run_virt_general.sh work on the intel platform? And which configs do I must enable in default .config, as the host kernel failed to startup with tpt_config on my server?

**Comment by shaiberg1** [comment]
Sorry about that!

There is some driver that is not configured / installed on the guest...

How did you create your guest Ubuntu image?

Can you try this one I've prepared (user: ubuntu pass: ubuntu)

https://www.dropbox.com/s/77dzn280973dpmm/ubuntu.img?dl=0

Lmk how it goes :)

**Comment by huster-hh** [comment]
Hi @shaiberg1 

It works for me!! Thanks!!

I generated my "ubuntu.img" based on "qemu-img create -f qcow2 ubuntu.img 250G". It seems not correct. How do you generate the correct "ubuntu.img"?

**Comment by shaiberg1** [comment]
Good to know!

What Ubuntu version did you install for the guest after you generated the image?

**Comment by huster-hh** [comment]
I am not sure what to do next? I usually used “virt-install” to create VMs, but not qemu-system-x86_64. I can include the Ubuntu ISO with “virt-install”. However, your scripts seem only include the "ubuntu.img" and the guest kernel bzImage. So what should I do after creating the "ubuntu.img" based on "qemu-img create"? Thanks ~

**Comment by shaiberg1** [comment]
Hey!

Sorry for the late reply. So there are a few options, you can add to the script a cdrom with the Ubuntu install, or better yet, generate an iso from a cloud image, you can use the scripts here

https://github.com/shaiberg1/virt

I'm closing this issue, but please don't hesitate to reopen it if you encounter any difficulties :)
