### ISSUE TITLE
Which Linux Kernel Base Version?

### ISSUE THREAD

**Issue by zz090923610** [acsl-technion/TPT#4]
Hi @shaiberg1 from your paper I know that your codes are based on Linux 5.16, but could you please specify which minor version? There are 5.16.1 to 5.16.20, or if you started from a Linux git, could you please specify the commit hash so we can do a diff? Thanks!

**Comment by zz090923610** [comment]
I assume the base version is https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.16.tar.gz , please correct me if I'm wrong, thanks!

**Comment by shaiberg1** [comment]
Hi!

It should be this commit df0cc57e057f18e44dac8e6c18aba47ab53202f9

I think the link you have is the correct version.

Please let me know if you see some wierd stuff in the diff and I'll pop on my server to see until which kernel commit I've squashed.

Thanks!
